---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp4d
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.ibm.com/Vishnu-Dinesh1/argocd-config
    targetRevision: main
    path: cp4d
  destination:
    server: https://kubernetes.default.svc
    namespace: cp4d