---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.cpd_operators_namespace }}"
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argo_namespace }}

---
apiVersion: v1
kind: Namespace
metadata:
    name: "{{ .Values.cpd_instance_namespace }}"
    labels:
      argocd.argoproj.io/managed-by: {{ .Values.argo_namespace }}

---
apiVersion: v1
kind: Namespace
metadata:
    name: "{{ .Values.cpd_cs_control_namespace }}"
    labels:
      argocd.argoproj.io/managed-by: {{ .Values.argo_namespace }}